### ISSUE TITLE
ID choose a court (no matching courts found): 
User Bug report
(`trial_court`)

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-Interpreternotice#16]
&nbsp; | &nbsp;
-------|------------------------------------
Steps to reproduce | After selecting a court, I get this error: Exception: showifdef() is invalid: 'user[0].phone_numbers()'
Expected behavior | I expected to see the next screen of the interview.
What happened instead | I got the error message.
Other information | Just testing but I thought you should know!
Question ID | choose a court (no matching courts found)
Variable being sought | trial_court
Package version | `1.2.2`
Filename | `docassemble.Interpreternotice:data/questions/interpreter_notice_standalone.yml`

**Comment by BryceStevenWilley** [comment]
Should be fixed!
