### ISSUE TITLE
id: basic questions intro screen

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-Interpreternotice#4]
You need to fix your metadata so the first screen says, "Ask the court for an interpreter "

**Comment by CaroRob** [comment]
Also this screen or metadata something needs to be adjusted so first screen doesn't tell you you can email the form to the court or the clerk

**Comment by cruck29** [comment]
I changed the first part "You need to fix your metadata so the first screen says, "Ask the court for an interpreter " and asked about the "email court or clerk" part.

**Comment by cruck29** [comment]
done.
