### ISSUE TITLE
 id: Interpreter notice

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-Interpreternotice#5]
I would change this question to a better name for the form, 
Notice of Interpreter Request
Use this form to ask the court for an interpreter in your case. 
## Your version
>The form helps non-English speaking defendant or plaintiffs fill the require the appointment of a court-paid (cost and fee) for non- English speaking interpreter to assist the defendant or plaintiff during civil action.

_Note:_ a non-English speaking interpreter would not be very helpful to a non-English speaking self represented litigant in our English speaking court system ;)

## Easier to read version
Give this form to the court if you need an interpreter.
 
The form tells the court:

- The language you need to be able to communicate with the court in, and
- You need the court to appoint and pay for an interpreter.

**Comment by cruck29** [comment]
done.
