### ISSUE TITLE
Some issues with Basic Questions - but not sure which .yml these are coming from 

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-Interpreternotice#7]
@nonprofittechy @colarusso @plocket 
Some of the language in the screens in this interview are coming from what seem like old Basic Questions which I think we revised. 
They need fixing but I am not sure which .yml (s) need me to create issues to fix these.

**Comment by nonprofittechy** [comment]
What language?

**Comment by CaroRob** [comment]
I think one of the questions was about user role - p v. d. I think we should stick with if you started the case language rather than telling people what their role is and then asking them the about the defendant Also the question is Are you A or are you B? That is the kind of question we are are trying to avoid. What is your I am happy to let people know they are plaintiff or defendant but not force them to remember that's what htey are to finish the interivew. Also I would like to see their answers be sentences. I am starting this case, I am responding to a case someone else started. or someone else is taking me to court... there were a couple of other questions I will go through and have a look at again - but I thought if I can get the right repo, I cna then use the question Id to refer to each one?

**Comment by nonprofittechy** [comment]
It's probably this question: https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/main/docassemble/AssemblyLine/data/questions/ql_baseline.yml#L83

**Comment by CaroRob** [comment]
I will go look at these later this week - thanks.
